#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
"""Generate xapian-letor exception headers (replaces generate-exceptions.pl).

Usage:
  python scripts/generate-letor-exceptions.py [--outdir DIR]
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

COPYRIGHT = """\
/* Copyright (C) 2003,2004,2006,2007,2008,2009,2011,2015,2019,2020 Olly Betts
 * Copyright (C) 2007 Richard Boulton
 * Copyright (C) 2016 Ayush Tomar
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, see
 * <https://www.gnu.org/licenses/>.
 */
"""

GENERATED = "/* Warning: This file is generated by generate-letor-exceptions.py - do not modify directly! */\n"

# (typecode, class, parent, synopsis, description)
CLASSES = [
    (
        0,
        "FileNotFoundError",
        "RuntimeError",
        "FileNotFoundError indicates that the file was not found at the path supplied.",
        "",
    ),
    (
        1,
        "LetorParseError",
        "RuntimeError",
        "LetorParseError indicates file parsing error.",
        "You should check that the file being parsed follows the standard set by\nxapian-letor.\n",
    ),
    (
        2,
        "LetorInternalError",
        "RuntimeError",
        "LetorInternalError indicates a runtime problem of some sort.",
        "",
    ),
]


def class_block(typecode: int, cls: str, parent: str, synopsis: str, description: str) -> str:
    code = f"\\{typecode:03o}"
    desc = ""
    if description.strip():
        desc = " *\n" + "".join(f" *  {line}\n" if line else " *\n" for line in description.splitlines())
        desc = desc.rstrip() + "\n"
    return f"""
/** {synopsis}
{desc} */
class XAPIAN_VISIBILITY_DEFAULT {cls} : public {parent} {{
  public:
    /** @private @internal
     *  @brief Private constructor for use by remote backend.
     *
     *  @param error_string_   Optional string describing error.  May be NULL.
     */
    {cls}(const std::string &msg_, const std::string &context_, const char * error_string_)
        : {parent}(msg_, context_, "{code}{cls}", error_string_) {{}}
    /** General purpose constructor.
     *
     *  @param msg_            Message giving details of the error, intended
     *                          for human consumption.
     *  @param context_        Optional context information for this error.
     *  @param errno_          Optional errno value associated with this error.
     */
    explicit {cls}(const std::string &msg_, const std::string &context_ = std::string(), int errno_ = 0)
        : {parent}(msg_, context_, "{code}{cls}", errno_) {{}}
    /** Construct from message and errno value.
     *
     *  @param msg_            Message giving details of the error, intended
     *                          for human consumption.
     *  @param errno_          Optional errno value associated with this error.
     */
    {cls}(const std::string &msg_, int errno_)
        : {parent}(msg_, std::string(), "{code}{cls}", errno_) {{}}
  protected:
    /** @private @internal
     *  @brief Constructor for use by constructors of derived classes.
     */
    {cls}(const std::string &msg_, const std::string &context_, const char * type_, const char * error_string_)
        : {parent}(msg_, context_, type_, error_string_) {{}}

    /** @private @internal
     *  @brief Constructor for use by constructors of derived classes.
     */
    {cls}(const std::string &msg_, const std::string &context_, const char * type_, int errno_)
        : {parent}(msg_, context_, type_, errno_) {{}}
}};
"""


def write_headers(outdir: Path) -> None:
    outdir.mkdir(parents=True, exist_ok=True)
    hdr = outdir / "letor_error.h"
    dispatch = outdir / "letor_errordispatch.h"

    with hdr.open("w", encoding="utf-8", newline="\n") as f:
        f.write("/** @file\n")
        f.write(" *  @brief Hierarchy of classes which xapian-letor can throw as exceptions.\n")
        f.write(" */\n")
        f.write(GENERATED)
        f.write(COPYRIGHT)
        f.write(
            """
#ifndef XAPIAN_INCLUDED_LETOR_ERROR_H
#define XAPIAN_INCLUDED_LETOR_ERROR_H

#include <xapian.h>

#include <string>
#include <xapian/attributes.h>
#include <xapian/visibility.h>

namespace Xapian {

/** All exceptions thrown by xapian-letor are subclasses of Xapian::Error.
 *
 *  Xapian::Error is defined in xapian-core/include/xapian/error.h
 *  xapian-letor error subclasses simply derive from the infrastructure defined over there
 */

"""
        )
        for typecode, cls, parent, synopsis, description in CLASSES:
            f.write(class_block(typecode, cls, parent, synopsis, description))
        f.write(
            """
}

#endif /* XAPIAN_INCLUDED_LETOR_ERROR_H */
"""
        )

    with dispatch.open("w", encoding="utf-8", newline="\n") as f:
        f.write(GENERATED)
        f.write(COPYRIGHT)
        for typecode, cls, _parent, _synopsis, _description in CLASSES:
            code = f"\\{typecode:03o}"
            f.write(f"case '{code}': throw Xapian::{cls}(msg, context, error_string);\n")
        f.write("#endif /* DOXYGEN */\n")


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--outdir",
        default=None,
        help="Directory for letor_error.h (default: third_party/xapian-letor/include/xapian-letor)",
    )
    args = ap.parse_args(argv)
    root = Path(__file__).resolve().parents[1]
    outdir = Path(args.outdir) if args.outdir else root / "third_party" / "xapian-letor" / "include" / "xapian-letor"
    write_headers(outdir)
    print(f"Wrote {outdir / 'letor_error.h'}")
    print(f"Wrote {outdir / 'letor_errordispatch.h'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
