# Auto-extracted from xapian-core 2.1.0 Makefile lib_src (all backends, no ICU).
set(XAPIAN_CORE_RELATIVE_SOURCES
  api/compactor.cc
  api/constinfo.cc
  api/database.cc
  api/decvalwtsource.cc
  api/document.cc
  api/documenttermlist.cc
  api/documentvaluelist.cc
  api/editdistance.cc
  api/enquire.cc
  api/error.cc
  api/expanddecider.cc
  api/keymaker.cc
  api/matchspy.cc
  api/mset.cc
  api/msetiterator.cc
  api/positioniterator.cc
  api/postingiterator.cc
  api/postingsource.cc
  api/query.cc
  api/queryinternal.cc
  api/rangeproc.cc
  api/registry.cc
  api/replication.cc
  api/result.cc
  api/rset.cc
  api/smallvector.cc
  api/sortable-serialise.cc
  api/terminfo.cc
  api/termiterator.cc
  api/termlist.cc
  api/valueiterator.cc
  api/valuesetmatchdecider.cc
  api/vectortermlist.cc
  backends/alltermslist.cc
  backends/contiguousalldocspostlist.cc
  backends/databasehelpers.cc
  backends/databaseinternal.cc
  backends/databasereplicator.cc
  backends/dbcheck.cc
  backends/dbfactory.cc
  backends/dbfactory_remote.cc
  backends/documentinternal.cc
  backends/empty_database.cc
  backends/flint_lock.cc
  backends/glass/glass_alldocspostlist.cc
  backends/glass/glass_alltermslist.cc
  backends/glass/glass_changes.cc
  backends/glass/glass_check.cc
  backends/glass/glass_compact.cc
  backends/glass/glass_cursor.cc
  backends/glass/glass_database.cc
  backends/glass/glass_databasereplicator.cc
  backends/glass/glass_dbcheck.cc
  backends/glass/glass_document.cc
  backends/glass/glass_freelist.cc
  backends/glass/glass_inverter.cc
  backends/glass/glass_metadata.cc
  backends/glass/glass_positionlist.cc
  backends/glass/glass_postlist.cc
  backends/glass/glass_spelling.cc
  backends/glass/glass_spellingwordslist.cc
  backends/glass/glass_synonym.cc
  backends/glass/glass_table.cc
  backends/glass/glass_termlist.cc
  backends/glass/glass_termlisttable.cc
  backends/glass/glass_valuelist.cc
  backends/glass/glass_values.cc
  backends/glass/glass_version.cc
  backends/honey/honey_alldocspostlist.cc
  backends/honey/honey_alltermslist.cc
  backends/honey/honey_check.cc
  backends/honey/honey_compact.cc
  backends/honey/honey_cursor.cc
  backends/honey/honey_database.cc
  backends/honey/honey_dbcheck.cc
  backends/honey/honey_document.cc
  backends/honey/honey_freelist.cc
  backends/honey/honey_inverter.cc
  backends/honey/honey_metadata.cc
  backends/honey/honey_positionlist.cc
  backends/honey/honey_postlist.cc
  backends/honey/honey_postlisttable.cc
  backends/honey/honey_spelling.cc
  backends/honey/honey_spellingwordslist.cc
  backends/honey/honey_synonym.cc
  backends/honey/honey_table.cc
  backends/honey/honey_termlist.cc
  backends/honey/honey_termlisttable.cc
  backends/honey/honey_valuelist.cc
  backends/honey/honey_values.cc
  backends/honey/honey_version.cc
  backends/inmemory/inmemory_alltermslist.cc
  backends/inmemory/inmemory_database.cc
  backends/inmemory/inmemory_document.cc
  backends/inmemory/inmemory_positionlist.cc
  backends/leafpostlist.cc
  backends/multi/multi_alltermslist.cc
  backends/multi/multi_database.cc
  backends/multi/multi_postlist.cc
  backends/multi/multi_termlist.cc
  backends/multi/multi_valuelist.cc
  backends/postlist.cc
  backends/remote/net_postlist.cc
  backends/remote/remote-database.cc
  backends/remote/remote-document.cc
  backends/remote/remote_alltermslist.cc
  backends/remote/remote_keylist.cc
  backends/remote/remote_termlist.cc
  backends/slowvaluelist.cc
  backends/uuids.cc
  backends/valuelist.cc
  common/bitstream.cc
  common/closefrom.cc
  common/compression_stream.cc
  common/debuglog.cc
  common/errno_to_string.cc
  common/fileutils.cc
  common/io_utils.cc
  common/keyword.cc
  common/msvc_dirent.cc
  common/omassert.cc
  common/pack.cc
  common/posixy_wrapper.cc
  common/replicate_utils.cc
  common/safe.cc
  common/serialise-double.cc
  common/socket_utils.cc
  common/str.cc
  expand/bo1eweight.cc
  expand/esetinternal.cc
  expand/expandweight.cc
  expand/ortermlist.cc
  expand/probeweight.cc
  geospatial/geoencode.cc
  geospatial/latlong_distance_keymaker.cc
  geospatial/latlong_metrics.cc
  geospatial/latlong_posting_source.cc
  geospatial/latlongcoord.cc
  languages/algorithms/arabic.cc
  languages/algorithms/armenian.cc
  languages/algorithms/basque.cc
  languages/algorithms/catalan.cc
  languages/algorithms/czech.cc
  languages/algorithms/danish.cc
  languages/algorithms/dutch.cc
  languages/algorithms/dutch_porter.cc
  languages/algorithms/earlymodernenglish.cc
  languages/algorithms/english.cc
  languages/algorithms/esperanto.cc
  languages/algorithms/estonian.cc
  languages/algorithms/finnish.cc
  languages/algorithms/french.cc
  languages/algorithms/german.cc
  languages/algorithms/greek.cc
  languages/algorithms/hindi.cc
  languages/algorithms/hungarian.cc
  languages/algorithms/indonesian.cc
  languages/algorithms/irish.cc
  languages/algorithms/italian.cc
  languages/algorithms/lithuanian.cc
  languages/algorithms/lovins.cc
  languages/algorithms/nepali.cc
  languages/algorithms/norwegian.cc
  languages/algorithms/persian.cc
  languages/algorithms/polish.cc
  languages/algorithms/porter.cc
  languages/algorithms/portuguese.cc
  languages/algorithms/romanian.cc
  languages/algorithms/russian.cc
  languages/algorithms/serbian.cc
  languages/algorithms/sesotho.cc
  languages/algorithms/spanish.cc
  languages/algorithms/swedish.cc
  languages/algorithms/tamil.cc
  languages/algorithms/turkish.cc
  languages/algorithms/yiddish.cc
  languages/snowball_runtime.cc
  languages/stem.cc
  matcher/andmaybepostlist.cc
  matcher/andnotpostlist.cc
  matcher/andpostlist.cc
  matcher/boolorpostlist.cc
  matcher/collapser.cc
  matcher/deciderpostlist.cc
  matcher/estimateop.cc
  matcher/exactphrasepostlist.cc
  matcher/externalpostlist.cc
  matcher/extraweightpostlist.cc
  matcher/localsubmatch.cc
  matcher/matcher.cc
  matcher/maxpostlist.cc
  matcher/msetcmp.cc
  matcher/nearpostlist.cc
  matcher/orpositionlist.cc
  matcher/orpospostlist.cc
  matcher/orpostlist.cc
  matcher/phrasepostlist.cc
  matcher/selectpostlist.cc
  matcher/synonympostlist.cc
  matcher/valuegepostlist.cc
  matcher/valuerangepostlist.cc
  matcher/valuestreamdocument.cc
  matcher/wrapperpostlist.cc
  matcher/xorpostlist.cc
  net/progclient.cc
  net/remoteconnection.cc
  net/remoteserver.cc
  net/remotetcpclient.cc
  net/replicatetcpclient.cc
  net/replicatetcpserver.cc
  net/serialise-error.cc
  net/serialise.cc
  net/tcpclient.cc
  net/tcpserver.cc
  queryparser/queryparser.cc
  queryparser/queryparser_internal.cc
  queryparser/termgenerator.cc
  queryparser/termgenerator_internal.cc
  queryparser/word-breaker.cc
  unicode/description_append.cc
  unicode/unicode-data.cc
  unicode/utf8itor.cc
  weight/bb2weight.cc
  weight/bm25plusweight.cc
  weight/bm25weight.cc
  weight/boolweight.cc
  weight/coordweight.cc
  weight/diceweight.cc
  weight/dlhweight.cc
  weight/dphweight.cc
  weight/ifb2weight.cc
  weight/ineb2weight.cc
  weight/inl2weight.cc
  weight/lmweight.cc
  weight/pl2plusweight.cc
  weight/pl2weight.cc
  weight/tfidfweight.cc
  weight/weight.cc
  weight/weightinternal.cc
)
