/* config.h generated by CMake — skeleton covering MSVC + common Unix needs.
 * Expand from upstream config.h.in as the port proceeds.
 * The MSVC large-file / warning block mirrors configure.ac AH_BOTTOM.
 */

#ifndef XAPIAN_CMAKE_CONFIG_H
#define XAPIAN_CMAKE_CONFIG_H

#define PACKAGE "@PACKAGE@"
#define PACKAGE_VERSION "@PACKAGE_VERSION@"
#define VERSION "@VERSION@"

#cmakedefine HAVE_UNISTD_H
#cmakedefine HAVE_SYS_STAT_H
#cmakedefine HAVE_ZLIB_H
#cmakedefine HAVE_FORK
#cmakedefine USE_WIN32_UUID_API

#define SIZEOF_SHORT @SIZEOF_SHORT@
#define SIZEOF_INT @SIZEOF_INT@
#define SIZEOF_LONG @SIZEOF_LONG@
#define SIZEOF_LONG_LONG @SIZEOF_LONG_LONG@

/* zlib wants const in signatures. */
#define ZLIB_CONST

/* Disable stupid MSVC warnings + large-file POSIX remapping.
 * Adapted from xapian-core configure.ac AH_BOTTOM.
 */
#ifdef _MSC_VER
# pragma warning(disable:4706)
# pragma warning(disable:4800)
# pragma warning(disable:4566)
# ifndef _CRT_NONSTDC_NO_WARNINGS
#  define _CRT_NONSTDC_NO_WARNINGS
# endif
# ifndef _CRT_SECURE_NO_WARNINGS
#  define _CRT_SECURE_NO_WARNINGS
# endif
# ifndef _WINSOCK_DEPRECATED_NO_WARNINGS
#  define _WINSOCK_DEPRECATED_NO_WARNINGS
# endif
# ifndef _USE_MATH_DEFINES
#  define _USE_MATH_DEFINES
# endif
# ifndef NOMINMAX
#  define NOMINMAX
# endif

# include <sys/stat.h>
# include <sys/types.h>
# include <io.h>
# include <zlib.h>

# ifdef stat
#  undef stat
# endif
# define stat _stat64

# ifdef fstat
#  undef fstat
# endif
# define fstat(FD, BUF) _fstat64(FD, BUF)

# ifdef lseek
#  undef lseek
# endif
# ifdef off_t
#  undef off_t
# endif
# define lseek(FD, OFF, WHENCE) _lseeki64(FD, OFF, WHENCE)
typedef long long off_t_redefinition_typedef;
# define off_t off_t_redefinition_typedef
#endif

/* MSVC defines _WIN32 but not __WIN32__. */
#if !defined __WIN32__ && defined _WIN32
# define __WIN32__
#endif
#if !defined __WIN64__ && defined _WIN64
# define __WIN64__
#endif

/* Branch-prediction stubs when builtins are absent. */
#ifndef rare
# define rare(COND) (COND)
# define usual(COND) (COND)
#endif

#endif /* XAPIAN_CMAKE_CONFIG_H */
